export const formatPrice = (price: number) => `$${price.toFixed(2)}`;

export const countryOptions = [
    { label: 'Afghanistan', value: 'Afghanistan' },
    { label: 'Åland Islands', value: 'Åland Islands' },
    { label: 'Albania', value: 'Albania' },
    { label: 'Algeria', value: 'Algeria' },
    { label: 'American Samoa', value: 'American Samoa' },
    { label: 'Andorra', value: 'Andorra' },
    { label: 'Angola', value: 'Angola' },
    { label: 'Anguilla', value: 'Anguilla' },
    { label: 'Antarctica', value: 'Antarctica' },
    { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
    { label: 'Argentina', value: 'Argentina' },
    { label: 'Armenia', value: 'Armenia' },
    { label: 'Aruba', value: 'Aruba' },
    { label: 'Asia/Pacific Region', value: 'Asia/Pacific Region' },
    { label: 'Australia', value: 'Australia' },
    { label: 'Austria', value: 'Austria' },
    { label: 'Azerbaijan', value: 'Azerbaijan' },
    { label: 'Bahamas', value: 'Bahamas' },
    { label: 'Bahrain', value: 'Bahrain' },
    { label: 'Bangladesh', value: 'Bangladesh' },
    { label: 'Barbados', value: 'Barbados' },
    { label: 'Belarus', value: 'Belarus' },
    { label: 'Belgium', value: 'Belgium' },
    { label: 'Belize', value: 'Belize' },
    { label: 'Benin', value: 'Benin' },
    { label: 'Bermuda', value: 'Bermuda' },
    { label: 'Bhutan', value: 'Bhutan' },
    { label: 'Bolivia', value: 'Bolivia' },
    { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
    { label: 'Botswana', value: 'Botswana' },
    { label: 'Bouvet Island', value: 'Bouvet Island' },
    { label: 'Brazil', value: 'Brazil' },
    { label: 'British Indian Ocean Territory', value: 'British Indian Ocean Territory' },
    { label: 'British Virgin Islands', value: 'British Virgin Islands' },
    { label: 'Brunei', value: 'Brunei' },
    { label: 'Bulgaria', value: 'Bulgaria' },
    { label: 'Burkina Faso', value: 'Burkina Faso' },
    { label: 'Burundi', value: 'Burundi' },
    { label: 'Cambodia', value: 'Cambodia' },
    { label: 'Cameroon', value: 'Cameroon' },
    { label: 'Cape Verde', value: 'Cape Verde' },
    { label: 'Caribbean Netherlands', value: 'Caribbean Netherlands' },
    { label: 'Cayman Islands', value: 'Cayman Islands' },
    { label: 'Central African Republic', value: 'Central African Republic' },
    { label: 'Chad', value: 'Chad' },
    { label: 'Chile', value: 'Chile' },
    { label: 'China', value: 'China' },
    { label: 'Christmas Island', value: 'Christmas Island' },
    { label: 'Cocos (Keeling) Islands', value: 'Cocos (Keeling) Islands' },
    { label: 'Colombia', value: 'Colombia' },
    { label: 'Comoros', value: 'Comoros' },
    { label: 'Congo', value: 'Congo' },
    { label: 'Cook Islands', value: 'Cook Islands' },
    { label: 'Costa Rica', value: 'Costa Rica' },
    { label: 'Cote d\'Ivoire', value: 'Cote d\'Ivoire' },
    { label: 'Croatia', value: 'Croatia' },
    { label: 'Cuba', value: 'Cuba' },
    { label: 'Curaçao', value: 'Curaçao' },
    { label: 'Cyprus', value: 'Cyprus' },
    { label: 'Czech Republic', value: 'Czech Republic' },
    { label: 'Democratic Republic of the Congo', value: 'Democratic Republic of the Congo' },
    { label: 'Denmark', value: 'Denmark' },
    { label: 'Djibouti', value: 'Djibouti' },
    { label: 'Dominica', value: 'Dominica' },
    { label: 'Dominican Republic', value: 'Dominican Republic' },
    { label: 'East Timor', value: 'East Timor' },
    { label: 'Ecuador', value: 'Ecuador' },
    { label: 'Egypt', value: 'Egypt' },
    { label: 'El Salvador', value: 'El Salvador' },
    { label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
    { label: 'Eritrea', value: 'Eritrea' },
    { label: 'Estonia', value: 'Estonia' },
    { label: 'Ethiopia', value: 'Ethiopia' },
    { label: 'Europe', value: 'Europe' },
    { label: 'Falkland Islands', value: 'Falkland Islands' },
    { label: 'Faroe Islands', value: 'Faroe Islands' },
    { label: 'Fiji', value: 'Fiji' },
    { label: 'Finland', value: 'Finland' },
    { label: 'France', value: 'France' },
    { label: 'French Guiana', value: 'French Guiana' },
    { label: 'French Polynesia', value: 'French Polynesia' },
    { label: 'French Southern and Antarctic Lands', value: 'French Southern and Antarctic Lands' },
    { label: 'Gabon', value: 'Gabon' },
    { label: 'Gambia', value: 'Gambia' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Germany', value: 'Germany' },
    { label: 'Ghana', value: 'Ghana' },
    { label: 'Gibraltar', value: 'Gibraltar' },
    { label: 'Greece', value: 'Greece' },
    { label: 'Greenland', value: 'Greenland' },
    { label: 'Grenada', value: 'Grenada' },
    { label: 'Guadeloupe', value: 'Guadeloupe' },
    { label: 'Guam', value: 'Guam' },
    { label: 'Guatemala', value: 'Guatemala' },
    { label: 'Guernsey', value: 'Guernsey' },
    { label: 'Guinea', value: 'Guinea' },
    { label: 'Guinea-Bissau', value: 'Guinea-Bissau' },
    { label: 'Guyana', value: 'Guyana' },
    { label: 'Haiti', value: 'Haiti' },
    { label: 'Heard Island and McDonald Islands', value: 'Heard Island and McDonald Islands' },
    { label: 'Honduras', value: 'Honduras' },
    { label: 'Hong Kong', value: 'Hong Kong' },
    { label: 'Hungary', value: 'Hungary' },
    { label: 'Iceland', value: 'Iceland' },
    { label: 'India', value: 'India' },
    { label: 'Indonesia', value: 'Indonesia' },
    { label: 'Iran', value: 'Iran' },
    { label: 'Iraq', value: 'Iraq' },
    { label: 'Ireland', value: 'Ireland' },
    { label: 'Isle of Man', value: 'Isle of Man' },
    { label: 'Israel', value: 'Israel' },
    { label: 'Italy', value: 'Italy' },
    { label: 'Jamaica', value: 'Jamaica' },
    { label: 'Japan', value: 'Japan' },
    { label: 'Jersey', value: 'Jersey' },
    { label: 'Jordan', value: 'Jordan' },
    { label: 'Kazakhstan', value: 'Kazakhstan' },
    { label: 'Kenya', value: 'Kenya' },
    { label: 'Kiribati', value: 'Kiribati' },
    { label: 'Kosovo', value: 'Kosovo' },
    { label: 'Kuwait', value: 'Kuwait' },
    { label: 'Kyrgyzstan', value: 'Kyrgyzstan' },
    { label: 'Laos', value: 'Laos' },
    { label: 'Latvia', value: 'Latvia' },
    { label: 'Lebanon', value: 'Lebanon' },
    { label: 'Lesotho', value: 'Lesotho' },
    { label: 'Liberia', value: 'Liberia' },
    { label: 'Libya', value: 'Libya' },
    { label: 'Liechtenstein', value: 'Liechtenstein' },
    { label: 'Lithuania', value: 'Lithuania' },
    { label: 'Luxembourg', value: 'Luxembourg' },
    { label: 'Macau', value: 'Macau' },
    { label: 'Macedonia (FYROM)', value: 'Macedonia (FYROM)' },
    { label: 'Madagascar', value: 'Madagascar' },
    { label: 'Malawi', value: 'Malawi' },
    { label: 'Malaysia', value: 'Malaysia' },
    { label: 'Maldives', value: 'Maldives' },
    { label: 'Mali', value: 'Mali' },
    { label: 'Malta', value: 'Malta' },
    { label: 'Marshall Islands', value: 'Marshall Islands' },
    { label: 'Martinique', value: 'Martinique' },
    { label: 'Mauritania', value: 'Mauritania' },
    { label: 'Mauritius', value: 'Mauritius' },
    { label: 'Mayotte', value: 'Mayotte' },
    { label: 'Mexico', value: 'Mexico' },
    { label: 'Micronesia', value: 'Micronesia' },
    { label: 'Moldova', value: 'Moldova' },
    { label: 'Monaco', value: 'Monaco' },
    { label: 'Mongolia', value: 'Mongolia' },
    { label: 'Montenegro', value: 'Montenegro' },
    { label: 'Montserrat', value: 'Montserrat' },
    { label: 'Morocco', value: 'Morocco' },
    { label: 'Mozambique', value: 'Mozambique' },
    { label: 'Myanmar (Burma)', value: 'Myanmar (Burma)' },
    { label: 'Namibia', value: 'Namibia' },
    { label: 'Nauru', value: 'Nauru' },
    { label: 'Nepal', value: 'Nepal' },
    { label: 'Netherlands', value: 'Netherlands' },
    { label: 'New Caledonia', value: 'New Caledonia' },
    { label: 'New Zealand', value: 'New Zealand' },
    { label: 'Nicaragua', value: 'Nicaragua' },
    { label: 'Niger', value: 'Niger' },
    { label: 'Nigeria', value: 'Nigeria' },
    { label: 'Niue', value: 'Niue' },
    { label: 'Norfolk Island', value: 'Norfolk Island' },
    { label: 'North Korea', value: 'North Korea' },
    { label: 'Northern Mariana Islands', value: 'Northern Mariana Islands' },
    { label: 'Norway', value: 'Norway' },
    { label: 'Oman', value: 'Oman' },
    { label: 'Pakistan', value: 'Pakistan' },
    { label: 'Palau', value: 'Palau' },
    { label: 'Palestine', value: 'Palestine' },
    { label: 'Panama', value: 'Panama' },
    { label: 'Papua New Guinea', value: 'Papua New Guinea' },
    { label: 'Paraguay', value: 'Paraguay' },
    { label: 'Peru', value: 'Peru' },
    { label: 'Philippines', value: 'Philippines' },
    { label: 'Pitcairn Islands', value: 'Pitcairn Islands' },
    { label: 'Poland', value: 'Poland' },
    { label: 'Portugal', value: 'Portugal' },
    { label: 'Puerto Rico', value: 'Puerto Rico' },
    { label: 'Qatar', value: 'Qatar' },
    { label: 'Réunion', value: 'Réunion' },
    { label: 'Romania', value: 'Romania' },
    { label: 'Russia', value: 'Russia' },
    { label: 'Rwanda', value: 'Rwanda' },
    { label: 'Saint Barthélemy', value: 'Saint Barthélemy' },
    { label: 'Saint Helena, Ascension and Tristan da Cunha', value: 'Saint Helena, Ascension and Tristan da Cunha' },
    { label: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis' },
    { label: 'Saint Lucia', value: 'Saint Lucia' },
    { label: 'Saint Martin', value: 'Saint Martin' },
    { label: 'Saint Pierre and Miquelon', value: 'Saint Pierre and Miquelon' },
    { label: 'Saint Vincent and the Grenadines', value: 'Saint Vincent and the Grenadines' },
    { label: 'Samoa', value: 'Samoa' },
    { label: 'San Marino', value: 'San Marino' },
    { label: 'São Tomé and Príncipe', value: 'São Tomé and Príncipe' },
    { label: 'Saudi Arabia', value: 'Saudi Arabia' },
    { label: 'Senegal', value: 'Senegal' },
    { label: 'Serbia', value: 'Serbia' },
    { label: 'Seychelles', value: 'Seychelles' },
    { label: 'Sierra Leone', value: 'Sierra Leone' },
    { label: 'Singapore', value: 'Singapore' },
    { label: 'Sint Maarten', value: 'Sint Maarten' },
    { label: 'Slovakia', value: 'Slovakia' },
    { label: 'Slovenia', value: 'Slovenia' },
    { label: 'Solomon Islands', value: 'Solomon Islands' },
    { label: 'Somalia', value: 'Somalia' },
    { label: 'South Africa', value: 'South Africa' },
    { label: 'South Georgia and the South Sandwich Islands', value: 'South Georgia and the South Sandwich Islands' },
    { label: 'South Korea', value: 'South Korea' },
    { label: 'South Sudan', value: 'South Sudan' },
    { label: 'Spain', value: 'Spain' },
    { label: 'Sri Lanka', value: 'Sri Lanka' },
    { label: 'Sudan', value: 'Sudan' },
    { label: 'Suriname', value: 'Suriname' },
    { label: 'Svalbard and Jan Mayen', value: 'Svalbard and Jan Mayen' },
    { label: 'Swaziland', value: 'Swaziland' },
    { label: 'Sweden', value: 'Sweden' },
    { label: 'Switzerland', value: 'Switzerland' },
    { label: 'Syria', value: 'Syria' },
    { label: 'Taiwan', value: 'Taiwan' },
    { label: 'Tajikistan', value: 'Tajikistan' },
    { label: 'Tanzania', value: 'Tanzania' },
    { label: 'Thailand', value: 'Thailand' },
    { label: 'Togo', value: 'Togo' },
    { label: 'Tokelau', value: 'Tokelau' },
    { label: 'Tonga', value: 'Tonga' },
    { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
    { label: 'Tunisia', value: 'Tunisia' },
    { label: 'Turkey', value: 'Turkey' },
    { label: 'Turkmenistan', value: 'Turkmenistan' },
    { label: 'Turks and Caicos Islands', value: 'Turks and Caicos Islands' },
    { label: 'Tuvalu', value: 'Tuvalu' },
    { label: 'U.S. Minor Outlying Islands', value: 'U.S. Minor Outlying Islands' },
    { label: 'U.S. Virgin Islands', value: 'U.S. Virgin Islands' },
    { label: 'Uganda', value: 'Uganda' },
    { label: 'Ukraine', value: 'Ukraine' },
    { label: 'United Arab Emirates', value: 'United Arab Emirates' },
    { label: 'United Kingdom', value: 'United Kingdom' },
    { label: 'Uruguay', value: 'Uruguay' },
    { label: 'Uzbekistan', value: 'Uzbekistan' },
    { label: 'Vanuatu', value: 'Vanuatu' },
    { label: 'Vatican City', value: 'Vatican City' },
    { label: 'Venezuela', value: 'Venezuela' },
    { label: 'Vietnam', value: 'Vietnam' },
    { label: 'Wallis and Futuna', value: 'Wallis and Futuna' },
    { label: 'Western Sahara', value: 'Western Sahara' },
    { label: 'Yemen', value: 'Yemen' },
    { label: 'Zambia', value: 'Zambia' },
    { label: 'Zimbabwe', value: 'Zimbabwe' }
  ];

  export const rifMinimums = {
    65: 4.00 / 100,
    66: 4.17 / 100,
    67: 4.35 / 100,
    68: 4.55 / 100,
    69: 4.76 / 100,
    70: 5.00 / 100,
    71: 5.28 / 100,
    72: 5.40 / 100,
    73: 5.53 / 100,
    74: 5.67 / 100,
    75: 5.82 / 100,
    76: 5.98 / 100,
    77: 6.17 / 100,
    78: 6.36 / 100,
    79: 6.58 / 100,
    80: 6.82 / 100,
    81: 7.08 / 100,
    82: 7.38 / 100,
    83: 7.71 / 100,
    84: 8.08 / 100,
    85: 8.51 / 100,
    86: 8.99 / 100,
    87: 9.55 / 100,
    88: 10.21 / 100,
    89: 10.99 / 100,
    90: 11.92 / 100,
    91: 13.06 / 100,
    92: 14.49 / 100,
    93: 16.34 / 100,
    94: 18.79 / 100,
    95: 20.00 / 100,
  };

  export const lifMinimums = {
    55: 2.86 / 100,
    56: 2.94 / 100,
    57: 3.03 / 100,
    58: 3.13 / 100,
    59: 3.23 / 100,
    60: 3.33 / 100,
    61: 3.45 / 100,
    62: 3.57 / 100,
    63: 3.70 / 100,
    64: 3.85 / 100,
    65: 4.00 / 100,
    66: 4.17 / 100,
    67: 4.35 / 100,
    68: 4.55 / 100,
    69: 4.76 / 100,
    70: 5.00 / 100,
    71: 5.28 / 100,
    72: 5.40 / 100,
    73: 5.53 / 100,
    74: 5.67 / 100,
    75: 5.82 / 100,
    76: 5.98 / 100,
    77: 6.17 / 100,
    78: 6.36 / 100,
    79: 6.58 / 100,
    80: 6.82 / 100,
    81: 7.08 / 100,
    82: 7.38 / 100,
    83: 7.71 / 100,
    84: 8.08 / 100,
    85: 8.51 / 100,
    86: 8.99 / 100,
    87: 9.55 / 100,
    88: 10.21 / 100,
    89: 10.99 / 100,
    90: 11.92 / 100,
    91: 13.06 / 100,
    92: 14.49 / 100,
    93: 16.34 / 100,
    94: 18.79 / 100,
    95: 20.00 / 100
  };
  
  export const provinceAndStateOptions = [
    { label: 'Alberta', value: 'Alberta' },
    { label: 'British Columbia', value: 'British Columbia' },
    { label: 'Manitoba', value: 'Manitoba' },
    { label: 'New Brunswick', value: 'New Brunswick' },
    { label: 'Newfoundland and Labrador', value: 'Newfoundland and Labrador' },
    { label: 'Northwest Territories', value: 'Northwest Territories' },
    { label: 'Nova Scotia', value: 'Nova Scotia' },
    { label: 'Nunavut', value: 'Nunavut' },
    { label: 'Ontario', value: 'Ontario' },
    { label: 'Prince Edward Island', value: 'Prince Edward Island' },
    { label: 'Quebec', value: 'Quebec' },
    { label: 'Saskatchewan', value: 'Saskatchewan' },
    { label: 'Yukon', value: 'Yukon' },
    { label: "Alabama", value: "Alabama" },
    { label: "Alaska", value: "Alaska" },
    { label: "Arizona", value: "Arizona" },
    { label: "Arkansas", value: "Arkansas" },
    { label: "California", value: "California" },
    { label: "Colorado", value: "Colorado" },
    { label: "Connecticut", value: "Connecticut" },
    { label: "Delaware", value: "Delaware" },
    { label: "Florida", value: "Florida" },
    { label: "Georgia", value: "Georgia" },
    { label: "Hawaii", value: "Hawaii" },
    { label: "Idaho", value: "Idaho" },
    { label: "Illinois", value: "Illinois" },
    { label: "Indiana", value: "Indiana" },
    { label: "Iowa", value: "Iowa" },
    { label: "Kansas", value: "Kansas" },
    { label: "Kentucky", value: "Kentucky" },
    { label: "Louisiana", value: "Louisiana" },
    { label: "Maine", value: "Maine" },
    { label: "Maryland", value: "Maryland" },
    { label: "Massachusetts", value: "Massachusetts" },
    { label: "Michigan", value: "Michigan" },
    { label: "Minnesota", value: "Minnesota" },
    { label: "Mississippi", value: "Mississippi" },
    { label: "Missouri", value: "Missouri" },
    { label: "Montana", value: "Montana" },
    { label: "Nebraska", value: "Nebraska" },
    { label: "Nevada", value: "Nevada" },
    { label: "New Hampshire", value: "New Hampshire" },
    { label: "New Jersey", value: "New Jersey" },
    { label: "New Mexico", value: "New Mexico" },
    { label: "New York", value: "New York" },
    { label: "North Carolina", value: "North Carolina" },
    { label: "North Dakota", value: "North Dakota" },
    { label: "Ohio", value: "Ohio" },
    { label: "Oklahoma", value: "Oklahoma" },
    { label: "Oregon", value: "Oregon" },
    { label: "Pennsylvania", value: "Pennsylvania" },
    { label: "Rhode Island", value: "Rhode Island" },
    { label: "South Carolina", value: "South Carolina" },
    { label: "South Dakota", value: "South Dakota" },
    { label: "Tennessee", value: "Tennessee" },
    { label: "Texas", value: "Texas" },
    { label: "Utah", value: "Utah" },
    { label: "Vermont", value: "Vermont" },
    { label: "Virginia", value: "Virginia" },
    { label: "Washington", value: "Washington" },
    { label: "West Virginia", value: "West Virginia" },
    { label: "Wisconsin", value: "Wisconsin" },
    { label: "Wyoming", value: "Wyoming" },
  ];

  export const provinceOptions = [
    { label: 'Alberta', value: 'Alberta' },
    { label: 'British Columbia', value: 'British Columbia' },
    { label: 'Manitoba', value: 'Manitoba' },
    { label: 'New Brunswick', value: 'New Brunswick' },
    { label: 'Newfoundland and Labrador', value: 'Newfoundland and Labrador' },
    { label: 'Northwest Territories', value: 'Northwest Territories' },
    { label: 'Nova Scotia', value: 'Nova Scotia' },
    { label: 'Nunavut', value: 'Nunavut' },
    { label: 'Ontario', value: 'Ontario' },
    { label: 'Prince Edward Island', value: 'Prince Edward Island' },
    { label: 'Quebec', value: 'Quebec' },
    { label: 'Saskatchewan', value: 'Saskatchewan' },
    { label: 'Yukon', value: 'Yukon' },
  ];

  export const legislationOptions = [
    { label: 'Alberta', value: 'Alberta' },
    { label: 'British Columbia', value: 'British Columbia' },
    { label: 'Federal', value: 'Federal' },
    { label: 'Manitoba', value: 'Manitoba' },
    { label: 'New Brunswick', value: 'New Brunswick' },
    { label: 'Newfoundland and Labrador', value: 'Newfoundland and Labrador' },
    { label: 'Nova Scotia', value: 'Nova Scotia' },
    { label: 'Ontario', value: 'Ontario' },
    { label: 'Quebec', value: 'Quebec' },
    { label: 'Saskatchewan', value: 'Saskatchewan' },
  ];

  export const relinquishingInstitutionList = [
    "3iQ",
    "A.F.T. Trivest Management Inc.",
    "ABC Funds",
    "AcceleRate Financial",
    "Access Credit Union",
    "Accilent Capital Management Inc.",
    "Achieva Financial",
    "Acker Finley Asset Management Inc.",
    "Acker Finley Inc.",
    "Acumen Capital",
    "ADVANCE SAVINGS CREDIT UNION",
    "AFBS - ACTRA Fraternal Benefit Society",
    "AFINA Capital Management Inc.",
    "AGF Investments",
    "AGF Securities Inc.",
    "Agilith Capital Inc.",
    "AIC Funds",
    "AIC Segregated Funds",
    "Aligned Capital Partners",
    "Alize Capital Inc.",
    "Allard, Allard et Associés Inc.",
    "Allexium Asset Management Inc.",
    "Allvista Investment Management Inc.",
    "AltaCorp Capital Inc.",
    "Alterna Savings",
    "Altervest Ltd.",
    "Altium Architecture de patrimoine Inc.",
    "American United Life Insurance Company",
    "Anchor Pacific Investment Management Corp",
    "Antares Investment Management Inc.",
    "Archer gestion de patrimoine inc",
    "ARGOSY SECURITIES INC",
    "Arrow Capital Management",
    "Artemis Investment Management Inc.",
    "ARX Capital Inc.",
    "ASIA - RBC Wealth Management",
    "Assante Capital / DPM Finacial Planning",
    "ASSANTE CAPITAL MANAGEMENT LTD",
    "Assante Wealth Management",
    "Assiniboine Credit Union",
    "Assumption Life",
    "AST / CST Trust Company (Canada)",
    "ATB Financial",
    "ATB Securities (Investor Services)",
    "ATB Securities Inc.",
    "Aventine Management Group Inc.",
    "Avenue Investment Management Inc.",
    "B2B Bank",
    "B2B Bank Financial Services Inc.",
    "B2B Bank Securities Services Inc.",
    "B2B Bank/MRS",
    "B2B Dealer Services",
    "B2B Trust",
    "Bank Audi - United Arab Emirates",
    "BANK OF NOVA SCOTIA",
    "Barometer Capital Management Inc.",
    "Barrantagh Investment Management",
    "Barreau Investments Funds",
    "Baskin Financial Services Inc.",
    "BBS Securities Inc.",
    "BCV Asset Management Inc.",
    "BEACON SECURITIES",
    "Beacon Securities Limited",
    "Bell Canada Pension Plan",
    "Bellwether Investment Management Inc.",
    "Beutel Goodman & Company Ltd.",
    "Beutel goodman and company ltd.",
    "BirchLeaf Investments Inc.",
    "BloombergSen Inc.",
    "Bluenose Investment Management Inc.",
    "BMG - Bullion Management Services Inc.",
    "BMO Bank of Montreal",
    "BMO Employee - ESOP",
    "BMO Harris Private Banking",
    "BMO Insurance",
    "BMO INVESTORLINE",
    "BMO Life Insurance",
    "BMO Mutual Funds",
    "BMO Nesbitt Burns",
    "BMO Wealth Management",
    "BNP PARIBAS FRANCE",
    "BNY Mellon Wealth Management, Advisory Services, Inc.",
    "Bombardier Pension Plan",
    "Botica Financial Group - Capital Management inc.",
    "Brandes Investment Partners",
    "Brant Securities Limited",
    "Bridgeport Asset Management Inc.",
    "Bridging finance inc.",
    "Bristol Gate Capital Partners Inc.",
    "BROADRIDGE USA",
    "Brookfield Financial Corp.",
    "Brownstone Asset Management Inc.",
    "BT Global Growth Inc.",
    "Budros, Ruhlin & Roe Inc.",
    "Bulkley Valley Credit Union",
    "Bull Wealth Management Group Inc",
    "BURGUNDY ASSET MANAGEMENT",
    "Bush Associates Ltd.",
    "C.I.C BANQUE TRANSATLANTIQUE FRANCE",
    "Caisse Desjardins",
    "Caisse Populaire Alliance limitee",
    "Caldwell Investment Management Ltd.",
    "Caldwell Securities",
    "Cambrian Credit Union",
    "Campbell, Lee & Ross Investment Management Inc.",
    "Canaccord Genuity Wealth Management",
    "Canada Life",
    "Canada Post Pension Plan",
    "Canada Savings Bond",
    "Canadian ShareOwner Investments Inc.",
    "Canadian Tire Bank",
    "Canadian Western Bank",
    "Canadian Western Trust",
    "Canadian Worker Co-op Federation",
    "Canoe Financial Funds",
    "Canso Investment Counsel Ltd.",
    "Capital Benoit Asset Management Inc",
    "Capital régional et coopératif Desjardins",
    "Capstone Capital Management Inc. (f.k.a Covenant Capital)",
    "Cardinal Capital Management Inc.",
    "Cardinal Point Capital Management Inc.",
    "Carecana management corp",
    "Cassels Investment Management Inc.",
    "CastleBay Wealth Management Inc",
    "Castlemoore Inc.",
    "CCQ - Commission de la contruction du Quebec",
    "CDSPI FUNDS",
    "Centurion Asset Management Inc.",
    "Century Management",
    "CGOV Asset Management",
    "CHARLES SCHWAB USA",
    "Children's Education Funds inc.",
    "Chinook Financial",
    "Chippingham Financial Group Ltd.",
    "Chronicle Investments Ltd.",
    "CI Investments",
    "CI PRIVATE COUNSEL LP",
    "CI Private Wealth",
    "CI Sun Wise Funds",
    "CIBC Bank",
    "CIBC Direct Brokerage (Wood Gundy)",
    "CIBC Investor Services Inc.",
    "CIBC Investors Edge",
    "CIBC Mellon - Funds",
    "CIBC Mutual Funds",
    "CIBC PPS - Personal Portfolio Services",
    "CIBC Private Investment Counsel",
    "CIBC Private wealth management",
    "CIBC Securities Inc.",
    "CIBC World Markets Inc.",
    "Cidel Asset Management Inc. (former Toron)",
    "CLAC - Christian Labour Association of Canada",
    "Clarus Securities Inc.",
    "Clearwater Capital Management",
    "Coast Captital",
    "Cockfield Porretti Cunningham Investment Counsel Inc.",
    "Coerente Captital Managment Inc.",
    "Coleford Investment Management Ltd.",
    "Community Trust",
    "Computershare",
    "Computershare - Private Capital Solutions",
    "Computershare - Trust Company of Canda",
    "Computershare USA",
    "Concentra Financial",
    "Condor Asset Management Inc.",
    "Connor, Clark & Lunn Investment Ltd.",
    "Connor, Clark & Lunn Private Capital Ltd.",
    "Co-operators Life Insurance Company",
    "Cornerstone Investment Counsel Ltd.",
    "Cote 100",
    "Counsel Portfolio Services",
    "Covington Capital Corporation" ,"Cowan Asset Management Inc",
    "Credential Asset Management",
    "Credential Securities",
    "Credit Union",
    "Crestridge Asset Management Inc.",
    "Crystal Wealth Management",
    "CST CONSULTANTS C.S.T INC",
    "CTI Capital",
    "CUA - Credit Union Atlantic",
    "Cumberland Associates",
    "Cumberland Private Wealth",
    "Cypress Capital Management Ltd.",
    "Da Vinci Capital",
    "Danske BANK - Denmark",
    "Davis-Rea Ltd.",
    "DE THOMAS WEALTH MANAGEMENT",
    "Delbrook Capital Advisors Inc.",
    "Delphina Asset Management Inc.",
    "Desjardins Financial Securities -– Investments",
    "Desjardins Financial Services Firm Inc.",
    "Desjardins Life Insurance",
    "Desjardins Online Brokerage",
    "Desjardins Securities",
    "Desjardins Trust",
    "Desjardins Wealth Management - Private Wealth Management",
    "Desjardins Wealth Management (Investments)",
    "Desjardins Wealth Management (Securities)",
    "Dixon & Patterson Financial Planning Inc.",
    "Dixon Mitchell Investment Counsel Inc.",
    "Doherty & Associates Ltd.",
    "Donations - Foundations",
    "Dorchester Wealth Management Company",
    "Dubeau Capital & Co.",
    "DUCA Credit Union Ltd",
    "DUNCAN ROSS",
    "Dundee Wealth Investment Counsel",
    "Dynamic Funds",
    "E*TRADE SECURITIES USA",
    "E.M. Smithies & Associates Investment Management Inc.",
    "Echelon Wealth Partners Inc.",
    "Edgecrest Capital",
    "EdgePoint Wealth Management Inc.",
    "EDUCATORS FINANCIAL GROUP INC.",
    "EDWARD JONES",
    "Effort Trust Company",
    "EFG Bank SA - CH",
    "Emerging Equities Inc.",
    "Empire Life",
    "Enriched Investing Incorporated",
    "ENVISION FINANCIAL",
    "Epargne Placements Quebec",
    "Equatex UK",
    "Equiniti USA",
    "Equitable Bank",
    "Equitable Life of Canada",
    "Equity Associates Inc.",
    "Estonian Credit Union",
    "ETF Capital Management Inc.",
    "Etrade USA",
    "Ewing Morris & Co. Investment Partners Ltd.",
    "Excel gestion privée",
    "Exponent Investment Management Inc.",
    "Fairbank Investment Management Ltd.",
    "Ferique Management",
    "FI Capital Ltd.",
    "Fidelity Clearing Canada",
    "Fidelity Investments",
    "Fidelity USA",
    "Fieldhouse Capital Management Inc.",
    "Fiera Capital Funds C/O IDFS",
    "Fiera Capital Inc.",
    "Fiera Investments LP, c/o IFDS",
    "First Calgary Financial",
    "First Island Financial Services Ltd.",
    "Fisgard Asset Management Corporation",
    "FMOQ - Fonds des Medecins Omnipraticiens du Quebec",
    "Focus Asset Management Ltd.",
    "Folger Nolan Fleming Douglas USA",
    "Fondaction CSN",
    "FONDATION UNIVERSITAS",
    "Foresters Asset Management Inc.",
    "Formula Growth Ltd.",
    "Forstrong Global Asset Management Inc.",
    "Foster & Associates",
    "Foyston, Gordon & Payne",
    "Franklin Templeton Investments",
    "Friedberg Mercantile Group Ltd.",
    "Frontwater Capital Inc.",
    "FTC - Fiduciary Trust Company of Canada",
    "FTQ - Fonds de Solidarite",
    "Fundex Investments",
    "G & F FINANCIAL",
    "Galileo Equity Management Inc.",
    "Galliant Advisors LP",
    "Genbridge Family Offices Inc.",
    "General Bank of Canada",
    "Generation Portfolio Management Corp.",
    "GENn Investment Counsel Ltd",
    "Genova Private Management",
    "GENUS CAPITAL MANAGEMENT INC.",
    "Georgian Capital Partners Corp.",
    "Gestion d'actif Stanton (Stanton Asset Management)",
    "Gestion de portefeuille stratégique Medici Inc.",
    "Gestion Privée Diamant",
    "Gestion Privée Phœnix S.A.",
    "GF Securities Canada",
    "GFI Investment Counsel Ltd.",
    "Giverny Capital Inc.",
    "Global Maxfin Capital Inc.",
    "Global Maxfin Investment Inc.",
    "Global Securities",
    "Globevest Capital Inc.",
    "GLUSKIN SHEFF & ASSOCIATES",
    "GMG Private Counsel",
    "GMP FirstEnergy",
    "Gold Investment Management Ltd.",
    "Golden Opportunities Fund",
    "Goodman and Company Investments Counsel Inc.",
    "Goodreid Investment Counsel",
    "Goodwood Inc.",
    "Government of Canada",
    "Gravitas Securities Inc.",
    "Grayhawk Investment Strategies Inc",
    "Great West Life - Assurance Company",
    "Greenrock Capital Partners Inc.",
    "Greenskeeper Asset Management Inc.",
    "Greystone Managed Investments Inc.",
    "Groupe Cloutier",
    "Growth Works Capital Funds",
    "Growthquest Capital Inc.",
    "Guardian Capital Advisors LP",
    "GWP Wealth Management Inc.",
    "Hampton Securities Ltd.",
    "Hang Seng Bank - Hong Kong",
    "Harbourfront Wealth Management Inc.",
    "Harmony Funds",
    "Harris, Bolduc & Associates",
    "HAYWOOD SECURITIES",
    "Headsail Wealth Management Inc.",
    "Heathbridge Capital Management Ltd.",
    "Hemisphere Capital Management Inc.",
    "Henley Capital Corporation",
    "Heritage Education Funds Inc.",
    "Heritage Yorkville Mutual Funds",
    "Heward Investment Management Inc.",
    "Higgins Investment Group Inc.",
    "Highstreet Asset Management Inc.",
    "Hillsdale Investment Management Inc.",
    "HNB - Anchor Investment Management Inc.",
    "HNW Management Inc.",
    "Hollis Wealth",
    "Home Trust Company",
    "HOOPP Pension Center",
    "Howard, Barclay & Associates Ltd.",
    "HSBC",
    "HSBC Private Wealth",
    "HSBC Securities",
    "HUB CAPITAL & FINANCIAL",
    "Hughes Little Investment Management Ltd.",
    "IA - Industrial Alliance Financial Group (Insurance)",
    "IA - Industrielle Alliance Securities (IAS)",
    "IA - Investia Financial",
    "IA Clarington Investments",
    "IceCap Asset Management Limited",
    "ICICI Bank Canada",
    "IEPP Investment Management Inc.",
    "IG Wealth management",
    "IGM Financial",
    "InfiniT",
    "INFOR Financial Inc.",
    "ING Direct",
    "Integral Wealth Securities Limited",
    "Interactive Brokers Canada Inc.",
    "Interior Savings Credit Union",
    "Inukshuk Capital Management Inc.",
    "Inverlochy Capital Ltd.",
    "Invesco Funds (AIM Trimark)",
    "Investax Management Inc.",
    "Investment Planning Counsel - Investment Corp.",
    "Investment Planning Counsel - Securities Corp.",
    "Investment Strategies Inc.",
    "Investors Group",
    "Investors Group Financial Services",
    "Investors Group Securities Inc",
    "IVARI (Transamerica Life)",
    "J Priest Investment Management",
    "J.C. Hood Investment Counsel",
    "J.P. Morgan USA",
    "Jacob Securities Inc.",
    "Japa International Ltd.",
    "Jarislowsky Fraser Limited",
    "JC Clark Ltd.",
    "Jefferies Securities Inc.",
    "JitneyTrade Inc.",
    "John S. Keenlyside & Company Ltd.",
    "Jones Collombin Investment Counsel Inc.",
    "Kassirer Asset Management Corporation",
    "Kawartha Credit Union",
    "KCM Wealth Management Inc. (acquired by LYCOS)",
    "Kernaghan & Partners LTD.",
    "Kerr Financial Advisors Inc.",
    "Keybase Financial Group",
    "Kilburn Ogilvie Waymann Investment Management Ltd.",
    "Kingsdale Capital Inc.",
    "Kingwest & Company",
    "KJ Harrison & Partners Inc.",
    "KNIGHTS OF COLUMBUS",
    "KNIGHTS OF COLUMBUS USA",
    "Knowledge First Financial",
    "La Capitale",
    "Lakeshore Securities",
    "Landry Investment Management Inc.",
    "Laurentian Bank",
    "Laurentian Bank Discount Brokerage",
    "Laurentian Bank Securities",
    "Laurus Investment Counseling",
    "LBC Financial Services",
    "LDIC Inc.",
    "Leede Financial",
    "Leede Jones Gable inc.",
    "Legacy Investment Services, Inc.",
    "Leith Wheeler Investment Counsel Ltd.",
    "Leon Frazer & Associates Inc.",
    "Les Investissements Rivemont Inc.",
    "Lester Asset Management",
    "LETKO, BROSSEAU & ASSOCIATES INC",
    "Level 3 Investment Management Inc.",
    "Lewin Capital Management Ltd.",
    "Liberty International Investment Management Inc.",
    "Lifewealth Inc.",
    "Lightwater Partners Ltd.",
    "LIGHTYEAR CAPITAL INC",
    "Linde Equity Inc.",
    "Lionguard Capital Management Inc.",
    "Lionridge Capital Management Inc.",
    "Liquidnet Canada Inc.",
    "Lissom Investment Management Inc.",
    "Local Authorities Pension Plan",
    "Logan Wealth Management Inc.",
    "London Life",
    "Longview Asset Management Ltd.",
    "Lorica Investment Counsel Inc.",
    "Lorne Steinberg Wealth Management Inc.",
    "Louisbourg investments - Institutional Management",
    "Louisbourg Investments - Private Wealth Management",
    "Lycos Asset Management Inc.",
    "Lyons Asset Management Inc.",
    "M Partners",
    "M.S. Lamont and Associates Ltd.",
    "Mackenzie Financial (Mutual Funds)",
    "Mackie Research Capital",
    "MacNicol & Associates Asset Management",
    "MACQUARIE",
    "Mahogany Asset Management Inc.",
    "Majestic Asset Management LLC",
    "Mandeville Private Client Inc.",
    "Manitou Investment Management Ltd.",
    "Manulife (Groupe Retirement)",
    "Manulife Bank",
    "Manulife Financial",
    "Manulife Investments",
    "Manulife Securities",
    "Manulife Securities Investment Services Inc.",
    "Maplewest Capital Corporation",
    "Marquest asset management inc.",
    "Marret Asset Management Inc.",
    "Martin, Lucas & Seagram Ltd.",
    "Matco financial inc",
    "Matco Financial Inc.",
    "Mawer Direct Investing LTD",
    "Mawer Investment Management Ltd. - Funds",
    "MCAN Mortgage Corporation",
    "McLean & Partners Wealth Management",
    "MD Financial Management",
    "MD Management Brokerage",
    "Meckelborg Financial Group Ltd.",
    "MERICI FIANCIAL SERVICES",
    "Meridian Credit Union",
    "Merrill Lynch USA",
    "MICA CAPITAL",
    "Middle Field Group - funds",
    "Milestone Investment Counsel Inc.",
    "Millar Private Wealth Management Inc.",
    "Mirabaud",
    "MIRABAUD CANADA INC.",
    "Monarch Wealth Corporation",
    "MONEY BLOCK USA",
    "Montag Private Wealth Inc.",
    "Morgan Meighen & Associates Ltd.",
    "Morgan Stanley Canada",
    "Morgan Stanley USA",
    "Morneau Shepell",
    "Most QC Portfolios",
    "MRS INC.",
    "National Bank Financial",
    "National Bank Insurance",
    "NATIXIS INTERÉPARGNE SERVICE",
    "NBC - National Bank of Canada",
    "NBDB - National Bank Direct Brokerage",
    "NBI - National Bank Investements",
    "NBT - National Bank Trust",
    "NCM Investments",
    "NCP Investment Management Inc.",
    "NEI - Northwest Mutual Funds",
    "Nelson & District Credit Union",
    "Nest Wealth Asset Management Inc.",
    "Newhaven Asset Management Inc.",
    "Newport Private Wealth Management Inc.",
    "Next Edge Capital Corp.",
    "Nicola Wealth Management",
    "Ninepoint Partners LP",
    "Norrep Capital Management Ltd.",
    "Nortel Networks Pension Plan",
    "North Growth Management",
    "North Shore Credit Union",
    "Northland Wealth Management Inc.",
    "Northwood Private Counsel Inc.",
    "Oaken Financial",
    "Odlum Brown",
    "Olympia Trust Company",
    "OMG Wealth Management Ltd.",
    "Omnivita Custom Wealth",
    "One Capital Management",
    "Open Access",
    "Optimize Wealth Management",
    "Optimum Asset Management",
    "Outlook Financial",
    "Overseas Financial institutions",
    "Pacific International Financial (PI Financial)",
    "Pacific Spirit Investment Management Inc.",
    "Pacifica Partners Inc.",
    "Padlock Investment Management Inc.",
    "Pallas Athena Investment Counsel",
    "Palos Management Inc.",
    "Pangaea Asset Management Inc.",
    "Paradigm Capital",
    "Paragon Private Wealth Inc.",
    "Park Capital Management (2012) Inc.",
    "Patrimonica Gestion d'actifs inc.",
    "Pavilion Advisory Group Ltd.",
    "Pavilion Global Markets Ltd.",
    "PEAK Investment Services",
    "PEAK Securities",
    "Pembroke Private Wealth Management",
    "Pension RRUQ",
    "Pension RTC",
    "PENSIONS",
    "Peoples Trust",
    "Perennial Asset Management",
    "Perimeter Markets Inc.",
    "Perron & Partners Wealth Management Corp.",
    "Perry Securities LTD.",
    "Pershing USA",
    "Peters & Co. Limited",
    "PFSL Investments",
    "Phillips Hagar & North (PHN)",
    "Placements Louis Journault",
    "PNC WEALTH MANAGEMENT - USA",
    "Polar Asset Management Partners Inc.",
    "Polaris Financial Inc.",
    "Pollitt & Co. Inc.",
    "Pollitt Investment Counsel Inc.",
    "Portfolio Management Corporation",
    "Portfolio Stewards Inc.",
    "Portfolio Strategies Corporation",
    "Prefontaine Capital Inc.",
    "Prime Quadrant LP",
    "Primerica",
    "Professionals Financial",
    "Professional's Financial",
    "Professionals Financial Funds",
    "Pugsley Capital Inc.",
    "Purpose Investments Inc.",
    "PWL Capital INC.",
    "Qtrade Asset Management Inc",
    "Qtrade Investor",
    "Quadrus Invesments",
    "QUBE Investment Management Inc.",
    "Queensbury securities inc",
    "Questrade",
    "QV Investors Inc.",
    "QVO VADIS Investment Management Inc.",
    "R.E.G.A.R. Gestion Privee Inc.",
    "Rae & Lipskie Investment Counsel Inc.",
    "Raintree Asset Management",
    "Raymond James",
    "Raymond James USA",
    "RBC Dexia",
    "RBC Direct Investing",
    "RBC Dominion Securities",
    "RBC LIFE INSURANCE",
    "RBC LIFE INSURANCE SEGRETATED FUNDS",
    "RBC Private Counsel USA",
    "RBC Royal Bank Funds",
    "RBC Royal Bank of Canada",
    "RBC Royal Bank of Canada - RMFI",
    "RBC ROYAL TRUST",
    "RBC Wealth Management",
    "RealCap Holdings Ltd.",
    "Reciever General of Canada",
    "Rempart Asset Management Inc.",
    "Renaissance Investments / CIBC Asset Management Inc.",
    "Retraite Quebec (CARRA & RRQ)",
    "RGF Integrated Wealth Management",
    "Richardson GMP Securities",
    "RN Croft Financial Inc.",
    "Robert Evans Investment Counsel Limited",
    "Rocklinc Investment Partners Inc.",
    "Rockvale (Stonebrooke) Capital Management Inc.",
    "Rogers Group Financial",
    "ROI Capital",
    "ROMSPEN MORTGAGE INVESTMENT FUND",
    "Rosen Partnership Inc.",
    "Rothenberg & Rothenberg",
    "Rothenberg Capital Management",
    "RPIA - Global fixed income experts",
    "Russell Investments Canada Ltd.",
    "Saskworks Venture Fund",
    "Schwaben Capital Group Ltd.",
    "Scotia Bank",
    "Scotia Capital",
    "Scotia iTrade",
    "Scotia McLeod",
    "Scotia Mortgage Corporation",
    "Scotia Private Investment Counsel",
    "Scotia Securities Inc.",
    "Scotia trust - The Bank of Nova Scotia Trust Company",
    "Scotia Wealth Management",
    "Scotiabank Advisor Deposit Services",
    "Seamark Asset Management Ltd.",
    "SECURIFONDS",
    "Secutor Capital Management Corp.",
    "SEI funds",
    "Sentry Investments",
    "Servus Credit Union",
    "Seven Hills Capital Corp.",
    "Seymour Investment Management Ltd",
    "SFL Investments",
    "SGGG Funds",
    "Sharp Asset Management Inc.",
    "Shaunessy Investment Counsel Inc.",
    "Sherbrooke Street Capital INC.",
    "Silver Heights Capital Management Inc.",
    "Simplii Financial / President's Choice",
    "Skyon Financial Corporation",
    "Slabe Inc.",
    "Slater Asset Management Inc",
    "SOCIETE GENERALE",
    "Solium Capital",
    "Soundvest Capital Management Ltd.",
    "Spartan Fund Management",
    "Sprott Private Wealth LP",
    "Sprung Investment Management Inc.",
    "SSQ Life Insurance",
    "Standard Life",
    "STEADYHAND INVESTMENT FUNDS INC.",
    "Steinbach Credit Union",
    "Stephen Avenue Securities Inc.",
    "Sterling Mutual",
    "St-Mauris Gestion de Placements",
    "Stonebrooke Asset Management Ltd. (Rockvale)",
    "Stonehouse Capital Management Inc.",
    "Stratigis Capital Advisors Inc.",
    "Stuart Investment Management",
    "Successful Investor Wealth Management Inc.",
    "Summerhill Capital Management Inc.",
    "Summus Investment Management Inc.",
    "Sun Life Financial",
    "SunTrust Banks USA",
    "T.E. Investment Counsel Inc.",
    "Tacita Capital Inc.",
    "Tangerine",
    "TCU Wealth Management",
    "TD Ameritrade USA",
    "TD Canada Trust",
    "TD Direct Investing",
    "TD Future Builder",
    "TD Mutual Funds",
    "TD Share Ownership & Equity Programs",
    "TD Waterhouse",
    "TD Wealth Management",
    "TD Wealth Private Investment Counsel",
    "Tempered Investment Management Ltd.",
    "Tempest Capital Corp.",
    "TenSquared Investments Inc.",
    "TFP Investment Counsel Corp.",
    "The Canadian Conference of Mennonite Brethren Churches",
    "The Compagnie Monégasque de Banque",
    "THE FAITHLIFE FINANCIAL",
    "THE MANUFACTURERS LIFE INSURANCE COMPANY",
    "The Murray Wealth Group Inc.",
    "Thornmark Asset Management Inc.",
    "Tower Asset Management",
    "Transition Financial Advisors Group, Inc.",
    "Trestle Asset Management Inc.",
    "Triasima",
    "Triasima Portfolio Management Inc.",
    "TriDelta Investment Management Inc.",
    "Triumph Asset Management Inc.",
    "TRUST ETERNA INC",
    "Tulett Mathews & Associates Inc.",
    "Turn8 Partners Inc.",
    "Turnpoint Wealth Management",
    "Turtle Creek Asset Management Inc.",
    "UBS Bank (Canada)",
    "UBS Bank USA",
    "Ullman Wealth Management Inc",
    "UNI Financial Cooperation",
    "Union Life Insurance",
    "USA - RBC Wealth Management",
    "Value Contrarian Asset Management Inc.",
    "Value Partners Investments Inc.",
    "Value Sciences Inc.",
    "Vancity Savings Credit Union",
    "Vantage Point Investment Management Inc.",
    "Venable Park Investment Counsel Inc.",
    "Venator Capital Management Ltd.",
    "Veritas Investment Research Corporation",
    "VERTEX FUND - Vertex One Asset Management",
    "Vertex One Asset Management Ltd.",
    "Vestcap Investment Management Inc.",
    "Viking Capital Corporation",
    "Virtual Brokers",
    "Visavis Investment Counsel Inc.",
    "W. Shupe & Company Investment Advisory Services Inc.",
    "W.A. Robinson Asset Management Ltd.",
    "W.D. Latimer Co. Ltd",
    "Waratah Capital Advisors Ltd.",
    "Waterstreet Family Capital Counsel Inc.",
    "Watson Di Primio Steel Investment Management Ltd.",
    "Watt Carmichael INC.",
    "Wawanesa",
    "WealthBar Financial Services Inc.",
    "Wealthbridge Investment Counsel Inc.",
    "WealthCo Asset Management Inc.",
    "Wealthsimple Inc.",
    "Wellington Altus Private Wealth",
    "Wells Asset Management System Inc.",
    "Wells Fargo Canada",
    "Wells Fargo USA",
    "Western Pacific Trust Company",
    "Whitehaven Securities Inc.",
    "Wickham Investment Counsel Inc.",
    "Windcroft Financial Counsel Limited",
    "Wise Capital Management Inc.",
    "WORKING OPPORTUNITY FUND",
    "Worldsource Financial Management",
    "Worldsource Securities",
    "Wutherich & Company Investment Counsel Inc.",
    "Yorkville Asset Management Inc.",
    "OTHER"
  ];
  

  export const getDateTimestampUtc = ({ year, month, date } = {}) => {
  if (year === undefined || month === undefined || date === undefined) {
    // throw new Error("Invalid arguments: year, month, and date are required.");
    //pass
  } else {
    const datetime = new Date(year, month, date);
    // Reset to midnight local time
    datetime.setHours(0, 0, 0, 0);
    // Adjust to UTC midnight if local time is not already UTC
    const utcMidnight = new Date(datetime.toISOString().slice(0, 11) + "00:00:00Z");
    // Convert to UNIX timestamp in milliseconds
    const unixTimestamp = utcMidnight.getTime();
    return unixTimestamp;
  }
};
